import { Inter } from "next/font/google";
import Logo from "../assets/logo-landing.svg"
import "./globals.css"
import { getServerSession } from "next-auth";
import SessionProvider from "../lib/SessionProvider";
import Navbar from "../components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "MedimeHub",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <head>
        <link rel="icon" href={Logo}/>
      </head>
      <body className={inter.className}>
        <SessionProvider session={session}>
            <Navbar />
            {children}
        </SessionProvider>
      </body>
    </html>
  );
}